import {Noto_Serif, Shippori_Mincho, Nunito} from 'next/font/google'
import {setRequestLocale} from 'next-intl/server'
import {NextIntlClientProvider, hasLocale} from 'next-intl'
import {notFound} from 'next/navigation'
import {routing} from '@/i18n/routing'
import React from 'react'
import type {Metadata} from 'next'
import '@/app/globals.css'
import {ThemeProvider} from 'next-themes'

//TODO: почему-то русский текст выглядит уродливо в этом шрифте, надо будет проверить
const notoSerif = Noto_Serif({
    subsets: ['latin-ext', 'cyrillic-ext'],
    weight: ['400', '700'],
    style: ['normal', 'italic'],
    variable: '--font-noto-serif'
})

const shipporiMincho = Shippori_Mincho({
    subsets: ['latin-ext'],
    weight: ['400', '700'],
    style: ['normal'],
    variable: '--font-shippori-mincho'
})

const nunito = Nunito({
    subsets: ['latin-ext', 'cyrillic-ext'],
    weight: ['400', '700'],
    style: ['normal'],
    variable: '--font-nunito'
})

type Props = {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}

export function generateStaticParams() {
    return routing.locales.map((locale: string) => ({locale}))
}

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function LocaleLayout({children, params}: Props) {
    const {locale} = await params

    if (!hasLocale(routing.locales, locale)) notFound()

    setRequestLocale(locale)

    return (
        <html lang={locale} suppressHydrationWarning>
        <body className={`${notoSerif.variable} ${shipporiMincho.variable} bg-(--main-colour) dark:bg-(--main-colour-dark) text-(--text-colour) dark:text-(--text-colour-dark)`}>
        <NextIntlClientProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                {children}
            </ThemeProvider>
        </NextIntlClientProvider>
        </body>
        </html>
    )
}