name: Synchronise Submodules

on:
  workflow_dispatch:

jobs:
  sync:
    name: 'Sync'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: true

      - name: Determine branch
        id: define-branch
        if: github.ref == 'refs/heads/main'
        run: |
          if [ ${{ github.ref }} -eq 'refs/heads/main' ]; then
            echo "::set-output name=branch::main"
          else
            echo "::set-output name=branch::test"

      - name: Git Submodule Update
        run: |
          git pull origin ${{ steps.define-branch.outputs.branch }} --recurse-submodules
          git submodule update --remote --recursive

      - name: Commit update
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.CI_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"